### ISSUE TITLE
USER STORY: Submitting poll choices

### ISSUE THREAD

**Issue by katepz** [katepz/Agile-Project#4]
As a **user** I can **submit my poll choices** so that **the website owner knows my opinion**

## Acceptance Criteria:

- Acceptance Criterion 1: there is a submit button
- Acceptance Criterion 2:
- Acceptance Criterion 3:

## Tasks

- [ ] Task 1 design submit button
- [ ] Task 2 create html and css for submit button
- [ ] Task 3 test functionality
