### ISSUE TITLE
USER STORY: give poll a limited time

### ISSUE THREAD

**Issue by katepz** [katepz/Agile-Project#7]
As a **website administrator** I can **set an expiry date** so that **I can hide the poll after a certain time**

## Acceptance Criteria:
- Acceptance Criterion 1: the poll closes after a pre-determined time
-  Acceptance Criterion 2: i can choose the length of time the poll stays open for

## Tasks

- [ ] Task 1 design option for administrator to select time for poll
- [ ] Task 2 write code for the above and embed
- [ ] Task 3 test functionality
